excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://mmacdonaldsilvercity.github.io
title: ITBlog
tagline: Reflections and ramblings on IT 
description: A long career, with a lot of different experiences, in corporate Information Technology provides a backdrop for observing the IT-scape.
paginate: 5